# Generated by Django 5.1.7 on 2025-03-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_fname', models.CharField(max_length=50)),
                ('f_lname', models.CharField(max_length=50)),
                ('f_Dob', models.CharField(max_length=50)),
                ('f_email', models.EmailField(max_length=254, unique='True')),
                ('f_phone', models.CharField(max_length=50)),
                ('Faculty_id', models.CharField(max_length=10)),
                ('join_date', models.CharField(max_length=20)),
                ('f_branch', models.CharField(choices=[('Select', 'Select'), ('CSE', 'CSE'), ('CE', 'CE'), ('ME', 'ME'), ('EEE', 'EEE'), ('EC', 'EC')], default='Select', max_length=6)),
                ('f_username', models.CharField(max_length=50, unique='True')),
                ('f_password', models.CharField(max_length=50, unique='True')),
            ],
        ),
        migrations.CreateModel(
            name='student_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_fname', models.CharField(max_length=50)),
                ('s_lname', models.CharField(max_length=50)),
                ('s_DOB', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254, unique='True')),
                ('sphone', models.CharField(max_length=50)),
                ('adm_no', models.CharField(max_length=50)),
                ('s_branch', models.CharField(choices=[('Select', 'Select'), ('CSE', 'CSE'), ('CE', 'CE'), ('ME', 'ME'), ('EEE', 'EEE'), ('EC', 'EC')], default='Select', max_length=6)),
                ('Semester', models.CharField(choices=[('0', 'Select'), ('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], default='Select', max_length=10)),
                ('univ_no', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique='True')),
                ('s_password', models.CharField(max_length=50, unique='True')),
            ],
        ),
    ]
