# Generated by Django 5.1.7 on 2025-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_faculty_login_f_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_login',
            name='f_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
