# Generated by Django 5.1.7 on 2025-03-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_login',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
