# Generated by Django 5.1.7 on 2025-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_alter_faculty_login_f_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_login',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
