# Generated by Django 5.1.7 on 2025-03-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_faculty_login_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_login',
            old_name='profile_picture',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='faculty_login',
            name='f_pic',
        ),
    ]
