# Generated by Django 5.1.7 on 2025-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_rename_profile_picture_student_login_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cefacaulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
            ],
        ),
    ]
