# Generated by Django 5.1.7 on 2025-04-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_cefacaulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cefacaulty',
            old_name='Position',
            new_name='Position_Qualification',
        ),
        migrations.RemoveField(
            model_name='cefacaulty',
            name='Qualification',
        ),
    ]
