# Generated by Django 5.1.7 on 2025-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_rename_position_cefacaulty_position_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cefacaulty',
            old_name='Position_Qualification',
            new_name='Position',
        ),
        migrations.AddField(
            model_name='cefacaulty',
            name='Qualification',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
