# Generated by Django 5.1.7 on 2025-04-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_rename_position_qualification_cefacaulty_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='csefacaulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
            ],
        ),
    ]
