# Generated by Django 5.1.7 on 2025-04-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_csefacaulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_login',
            name='role',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
