# Generated by Django 5.1.7 on 2025-04-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_studentsubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('admission_no', models.CharField(max_length=255)),
                ('university_no', models.CharField(max_length=255)),
                ('Branch', models.CharField(choices=[('Select', 'Select'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical'), ('CSE', 'Computer Science'), ('CE', 'Civil Engineering '), ('EC', 'Electroncs')], default='Select', max_length=6)),
                ('Tutor', models.CharField(max_length=255)),
                ('HoD', models.CharField(max_length=255)),
                ('Principal', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=500)),
                ('Details', models.CharField(max_length=1500)),
            ],
        ),
    ]
