# Generated by Django 5.1.7 on 2025-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0020_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='Semester',
            field=models.CharField(choices=[('0', 'Select'), ('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'S7'), ('8', 'S8')], default='Select', max_length=10),
        ),
    ]
