# Generated by Django 5.1.7 on 2025-05-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0022_hodapproval_tutorapprovalform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='Tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.faculty_login'),
        ),
    ]
