# Generated by Django 5.1.7 on 2025-05-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0023_alter_application_form_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapprovalform',
            name='HoD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.faculty_login'),
            preserve_default=False,
        ),
    ]
