# Generated by Django 5.1.7 on 2025-05-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0024_tutorapprovalform_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(choices=[('Select', 'Select'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical'), ('CSE', 'Computer Science'), ('CE', 'Civil Engineering '), ('EC', 'Electroncs')], default='Select', max_length=6)),
                ('Semester', models.CharField(choices=[('Select', 'Select'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical'), ('CSE', 'Computer Science'), ('CE', 'Civil Engineering '), ('EC', 'Electroncs')], default='Select', max_length=6)),
                ('Subject', models.CharField(max_length=500)),
                ('Student_name', models.CharField(max_length=255)),
                ('Register_no', models.CharField(max_length=255)),
                ('Period', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='select', max_length=6)),
                ('Date', models.DateField()),
                ('Attendance', models.CharField(choices=[('True', 'Present'), ('False', 'Absents')], default='Select', max_length=6)),
            ],
        ),
    ]
