# Generated by Django 5.1.7 on 2025-05-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0025_attendance_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentsubjects',
        ),
    ]
