# Generated by Django 5.1.7 on 2025-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0027_studentsubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='asfaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ecefaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='eeefaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mefaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
            ],
        ),
    ]
